
log_path: ./logs.log
paths:
  result_path: ./trt_files
  output_path: outputs
  log_file: logfile.log


model:
  onnx_file_path: "model.onnx"
  input_min_size: "assign it according to your networks"
  input_opt_size: "assign it according to your networks"
  input_max_size: "assign it according to your networks"

calibrator:
  quantization_mode: int8 #fp32, fp16 or int8
  file_path: "your calibration data path"





